export type MoodType = 'Bored' | 'Adventurous' | 'Relaxed' | 'Social' | 'Romantic' | 'Curious';

export type GroupType = 'Solo' | 'Friends' | 'Partner' | 'Family';

export interface MoodOption {
  id: MoodType;
  label: string;
  tagline: string;
}

export interface GroupOption {
  id: GroupType;
  label: string;
  tagline: string;
}

/**
 * Conceptual structure for the user's validated preferences object:
 * Source of truth for the user's request.
 */
export interface PlanoraPreferences {
  mood: string;
  budget: number;
  groupType: string;
  location: string;
  latitude: number | null;
  longitude: number | null;
  date: string;
}

export interface PlanningFormState {
  mood: string;
  budget: string;
  groupType: string;
  location: string;
  latitude: number | null;
  longitude: number | null;
  date: string;
}

export interface FormErrors {
  mood?: string;
  budget?: string;
  groupType?: string;
  location?: string;
  date?: string;
}

/**
 * Normalized structure for real-world places and events:
 * Canonical Planora schema ready for downstream recommendation layers.
 */
export interface NormalizedPlanoraItem {
  id: string;
  name: string;
  type: 'place' | 'event';
  category: string;
  description: string;
  location: string;
  latitude: number | null;
  longitude: number | null;
  price: number | null;
  date: string | null;
  sourceName: string;
  sourceUrl: string | null;
}

export type DataSourceStatus = 'live' | 'unconfigured' | 'error';

export interface DataRetrievalResult<T> {
  data: T;
  status: DataSourceStatus;
  source: string;
  message: string;
  timestamp: string;
  queryParameters?: Record<string, unknown>;
}

export interface OutingDataResponse {
  placesResult: DataRetrievalResult<NormalizedPlanoraItem[]>;
  eventsResult: DataRetrievalResult<NormalizedPlanoraItem[]>;
  allNormalizedItems: NormalizedPlanoraItem[];
  isConfigured: boolean;
}

/**
 * Validated recommendation produced by Gemini reasoning over real-world items.
 */
export interface PlanoraRecommendation {
  itemId: string;
  item: NormalizedPlanoraItem;
  reason: string;
  estimatedCost: number | null;
  suitabilityScore: number;
}

export interface RecommendationResponse {
  recommendations: PlanoraRecommendation[];
  status: 'success' | 'empty' | 'error';
  message: string;
}

/**
 * Individual stop in a multi-stop outing plan, bound to an authentic item.
 */
export interface OutingPlanStop {
  itemId: string;
  order: number;
  reason: string;
  item: NormalizedPlanoraItem;
  estimatedCost: number | null;
}

/**
 * Complete multi-stop outing itinerary generated by Gemini reasoning over real items.
 */
export interface OutingPlan {
  id: string;
  title: string;
  description: string;
  stops: OutingPlanStop[];
  estimatedTotalCost: number | null;
  budgetStatus: 'within_budget' | 'unknown' | 'over_budget';
}

export interface OutingPlansResponse {
  plans: OutingPlan[];
  status: 'success' | 'empty' | 'error';
  message: string;
}


